### PR TITLE
Add terratest

### PR DESCRIPTION
**Pull request by oscr**
Adds a simple terratest that just applies the examples to ensure that they work as expected.

### CODE REVIEW

**Comment by drewmullen** [comment]
hi @oscr! thanks for submitting this PR. I wanted to draw your attention to #4 which is an alternate approach to testing these modules using native Terraform Test. The feature is experimental but... so is `awscc` technically (and Terraform prior to June 2021 🤣 ). 

I'm exploring the idea of standardizing the I&A modules on `terraform test` since its likely to be non-experimental One Day™. Please let me know what you think about each approach.

**Comment by oscr** [comment]
Hi @drewmullen! First of all congratulations on joining the I&A team! It’s going to be great working with you and learning together. I think it’s awesome that you took the time to make a counter proposal. That’s really going the extra mile so thank you for that.

Having looked at #4 I think terraform tests look promising. They are clean and don't require external dependencies like terratest. Your work with writing the tests is great. The question is as you mention how long is it until it becomes “non-experimental”? Is it even being actively developed? The documentation warns that it will likely undergo significant changes. 

Until it’s clear that terraform test is being prioritized and close to stable, I think it has the potential to detract from the main goal of the modules: to get them production ready with the awscc provider. I therefore think that for now we should continue with terratest which is stable, mature and has a large community backing.

**Comment by oscr** [comment]
@drewmullen @andrew-glenn What is the status here? Should I abandon this PR?

**Comment by drewmullen** [comment]
Thanks for your patience. I'm still waiting on feedback from the team to form a consensus. In my exploration of `terraform test` I did find some [decent size bugs](https://github.com/hashicorp/terraform/issues/30133). That being said, Hashi has been very responsive to my issues and topics in discuss.hashicorp.com so I'm hopeful on the outlook of the feature.

My vote is `terraform test` > `terratest` except for when we find test cases that `terraform test` cannot handle yet.

**Comment by oscr** [comment]
I don't think module development should be hindered because we're waiting for terraform test. I think we should continue with terratest which works right now, and in 6 months or so revisit terraform test again. The choice between the two isn't set in stone.

**Comment by andrew-glenn** [comment]
+1, especially given the current time of year, a fair number of folks are taking holiday. We don't want that to hinder any spare time you may have to devote to this and similar efforts

**Comment by drewmullen** [comment]
I actually think i just found another bug in `terraform test` 😑  so I'm actually leaning to agree with you that we should revisit the tool when they do their 2nd release. im a huge fan of what theyre putting together it just might not be quite ready for prime time. 

Again thanks for the patience while we vet the options available and for the contribution

**Pull request merged**
